# Generated by Django 2.1.1 on 2018-11-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCs',
            fields=[
                ('subno', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('bal', models.DecimalField(blank=True, decimal_places=6, max_digits=26, null=True)),
                ('bal_c', models.DecimalField(blank=True, decimal_places=6, max_digits=26, null=True)),
            ],
            options={
                'db_table': 'data_cs',
                'managed': False,
            },
        ),
    ]
