# Generated by Django 2.1.1 on 2018-11-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meiri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMova',
            fields=[
                ('branchno', models.IntegerField(primary_key=True, serialize=False)),
                ('subno', models.IntegerField()),
                ('date', models.DateField()),
                ('bal', models.DecimalField(blank=True, decimal_places=6, max_digits=26, null=True)),
                ('bal_c', models.DecimalField(blank=True, decimal_places=6, max_digits=26, null=True)),
            ],
            options={
                'db_table': 'data_mova',
                'managed': False,
            },
        ),
    ]
